# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "docker.do4.lab"
    docker.vm.network "private_network", ip: "192.168.89.140"
    docker.vm.network "forwarded_port", guest: 80, host: 8080
    docker.vm.provision "shell", path: "ntp.sh"
    docker.vm.provision "shell", path: "chef-workst.sh"
    docker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end
  end
end
